Log more information when deep-compare fails
We're trying to track down issues at Airbnb where deep comparisons
(where compareThreshold is set) fails with inactionable error messages:

Error: Unexpected end of input

This could either be a corrupt image file or some other network issue
along the way. In order to track this down further, I'm adding one last
fetch without piping the response to pngjs, just to be able to log
details about what that URL responds with. Thing like:
- status code
- headers
- body

Hopefully this will help us track down loading issues further.