Avoid touching lockfiles when installing dependencies
A customer reported that the happo-ci script failed intermittently due
to package-lock.json being modified as part of the `npm install`.

  error: Your local changes to the following files would be overwritten by checkout:
      package-lock.json
  Please, commit your changes or stash them before you can switch branches.

Yarn has a --pure-lockfile flag to prevent yarn.lock from being touched.
https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-pure-lockfile

Finding a flag for npm was trickier. I think the real fix is to use `npm
ci`, https://docs.npmjs.com/cli/ci. But I don't want to introduce that
change right now as I know too little of the side-effects. Instead, the
--no-save flag seems to do the trick, as verified locally and in this
npm issue:
https://github.com/npm/npm/issues/17761