Catch errors during webpack compilation
I was making the assumption that any compilation error is sent back
through the error parameter. But it turns out that things might
"succeed" yet still have compilation issues. By reaching in to the stats
we can reject compilation if there are errors.

For now I'm making the assumption that one error is enough to take
action on.

This should fix issues where running happo fails with something like
"Error: Could not load script: "/tmp/happo-bundle-react-L3dvcmtzcGFjZQ==.js"