Ignore publicFolders that don't descend from cwd
...but only when using `prerender:false`. Because we need to create a
static zip package with all the content in public folders, we need to
make sure they're part of the current project.

This commit fixes an error I saw when trying 3.14.0-rc.1 in the wild:

Error: Public folder /var/folders/1l/_t6tm7195nd53936tsvh2pcr0000gn/T/happo-tmp-68f6f is n
t a descendant of cwd (function () {
  if (!cwd)
    cwd = origCwd.call(process)
  return cwd
})